services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3093:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - webnet

networks:
  webnet: